import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { AngularFireModule } from 'angularfire2';

// diretives and providers
import { Loader } from '../providers/loader';
import { Nl2br } from '../pipes/nl2br';
import { HoursMinutesSeconds } from '../pipes/hours-minutes-seconds';
import { AuthenticatorService } from '../providers/authenticator';
import { Ionic2Rating } from 'ionic2-rating';

// Custom pages generated by ionic generator
import { HomePage } from '../pages/home/home';
import { SettingsPage } from '../pages/settings/settings';
import { ShoppingListPage } from '../pages/shopping-list/shopping-list';
import { TabsPage } from '../pages/tabs/tabs';
import { TimerPage } from '../pages/timer/timer';
import { SearchPage } from '../pages/search/search';
import { DetailsPage } from '../pages/details/details';
import { Category1Page } from '../pages/categories/category-1/category-1';
import { Category2Page } from '../pages/categories/category-2/category-2';
import { Category3Page } from '../pages/categories/category-3/category-3';
import { Category4Page } from '../pages/categories/category-4/category-4';
import { Category5Page } from '../pages/categories/category-5/category-5';
import { Category6Page } from '../pages/categories/category-6/category-6';
import { Category7Page } from '../pages/categories/category-7/category-7';
import { Category8Page } from '../pages/categories/category-8/category-8';
import { Category9Page } from '../pages/categories/category-9/category-9';
import { Category10Page } from '../pages/categories/category-10/category-10';
import { Category11Page } from '../pages/categories/category-11/category-11';
import { Category12Page } from '../pages/categories/category-12/category-12';

// Authentication
import { LoginPage } from '../pages/authentication/login/login';
import { RegistrationPage } from '../pages/authentication/registration/registration';

import { Config } from './config'

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    TabsPage,
    SearchPage,
    ShoppingListPage,
    TimerPage,
    DetailsPage,
    Category1Page,
    Category2Page,
    Category3Page,
    Category4Page,
    Category5Page,
    Category6Page,
    Category7Page,
    Category8Page,
    Category9Page,
    Category10Page,
    Category11Page,
    Category12Page,
    SettingsPage,
    LoginPage,
    RegistrationPage,
    Nl2br,
    HoursMinutesSeconds,
    Ionic2Rating,
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(Config.FIREBASE_CONFIG),
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    TabsPage,
    SearchPage,
    ShoppingListPage,
    TimerPage,
    Category1Page,
    Category2Page,
    Category3Page,
    Category4Page,
    Category5Page,
    Category6Page,
    Category7Page,
    Category8Page,
    Category9Page,
    Category10Page,
    Category11Page,
    Category12Page,
    DetailsPage,
    LoginPage,
    RegistrationPage,
    SettingsPage
  ],
  providers: [
    Loader,
    AuthenticatorService
  ]
})
export class AppModule {}
